namespace: stepup

app:
  name: stepup-app
  image: awarenivrutti11/stepup-app
  tag: v2
  replicas: 2
  service:
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: 30007

config:
  APP_NAME: "StepUp Java Application"
  APP_ENV: "prod"
  SERVER_PORT: "8080"
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: stepupdb

secrets:
  DB_USERNAME: stepup
  DB_PASSWORD: stepup123

mysql:
  image: mysql
  tag: "8.0"
  database: stepupdb
  user: stepup
  password: stepup123
  rootPassword: root123
  storage: 2Gi

