apiVersion: apps/v1
kind: Deployment
metadata:
  name: stepup-app
  namespace: stepup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stepup
  template:
    metadata:
      labels:
        app: stepu
    spec:
      containers:
      - name: stepup
        image: awarenivrutti11/stepup-app:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: stepup-config
        - secretRef:
            name: stepup-secret

