apiVersion: v1
kind: ConfigMap
metadata:
  name: stepup-config
  namespace: stepup
data:
  APP_NAME: "StepUp Java Application"
  APP_ENV: "prod"
  SERVER_PORT: "8080"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "stepupdb"

