apiVersion: apps/v1
kind: Deployment
metadata:
  name: stepup-app
  namespace: stepup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stepup
  template:
    metadata:
      labels:
        app: stepup
    spec:
      containers:
        - name: stepup
          image: awarenivrutti11/stepup-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

