apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: stepup
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw==   # root123
  MYSQL_USER: c3RlcHVw                # stepup
  MYSQL_PASSWORD: c3RlcHVwMTIz         # stepup123

