apiVersion: v1
kind: Service
metadata:
  name: stepup-service
  namespace: stepup
spec:
  type: NodePort
  selector:
    app: stepup
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007

