apiVersion: v1
kind: Secret
metadata:
  name: stepup-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.DB_USERNAME | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc }}

