apiVersion: v1
kind: Service
metadata:
  name: stepup-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: stepup
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      nodePort: {{ .Values.app.service.nodePort }}

